services:
  go-web-app:
    image: cosmtrek/air
    working_dir: /src
    ports:
      - "3001:3001"
    volumes:
      - ./:/src/
      - ./cmd/rest/main.go:/src/main.go
    restart: always
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ta-spbe
      POSTGRES_USER: ta-spbe
      POSTGRES_PASSWORD: ta-spbe
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.27
    expose:
      - "16686"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    expose:
      - "4317"
      - "4318"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    volumes:
      - "${PWD}/configs/instrumentation/otelcollector:/observability"
      - ./configs/instrumentation/otelcollector/otel-collector.json:/etc/otel/key.json
    command: ["--config=/observability/otel-config.yaml", "${OTELCOL_ARGS}"]
    restart: always
    depends_on:
      - jaeger


  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - ./configs/instrumentation/metric/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devops123
    volumes:
      - ./configs/instrumentation/metric/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
volumes:
  pgdata:
  grafanadata:
  prometheusdata: