services:
  go-app:
    image: cosmtrek/air
    working_dir: /src
    ports:
      - "8080:8080"
    volumes:
      - ./:/src/
    depends_on: 
      - postgres
      - nsqd
    restart: always

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ta-spbe
      POSTGRES_USER: ta-spbe
      POSTGRES_PASSWORD: ta-spbe
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nsqlookupd:
    image: nsqio/nsq
    restart: always
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    restart: always
    command:  /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4151:4151"
      - "4150:4150"
  nsqadmin:
    image: nsqio/nsq
    restart: always
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - ./instrumentation/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devops123
    volumes:
      - ./instrumentation/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-storage:/var/lib/grafana
  jaeger:
    image: jaegertracing/all-in-one:1.27
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    expose:
      - "16686"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: always
  
volumes:
  pgdata:
  grafana-storage: