version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ta-spbe
      POSTGRES_USER: ta-spbe
      POSTGRES_PASSWORD: ta-spbe
    ports:
      - "5433:5432"