version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=ec2-52-221-192-157.ap-southeast-1.compute.amazonaws.com
      - LETSENCRYPT_HOST=ec2-52-221-192-157.ap-southeast-1.compute.amazonaws.com