version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - nsqd
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ta-spbe
      POSTGRES_USER: ta-spbe
      POSTGRES_PASSWORD: ta-spbe
    ports:
      - "5433:5432"
  nsqlookupd:
    image: nsqio/nsq
    restart: always
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    restart: always
    command:  /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4151:4151"
      - "4150:4150"
  nsqadmin:
    image: nsqio/nsq
    restart: always
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  nlp-processing:
    build: ./ext-service/nlp-processing
    restart: always
    ports:
      - "8000:15400"
    volumes:
      - ./ext-service/nlp-processing/app/:/app/src